### ISSUE TITLE
npm run setup, pm2 start ecosystem.config.js 코드 입력시 에러 발생 합니다.

### ISSUE THREAD

**Issue by seongyeop-jeong-poey** [danieluhm2004/chaingram#10]
안녕하세요.

위의 두 코드 입력시, 아래와 같은에러가 발생합니다.
![image](https://user-images.githubusercontent.com/37603367/136548568-ee914e1a-6ab7-47f9-8e0b-bdf1957ff910.png)
![image](https://user-images.githubusercontent.com/37603367/136548596-1ff5c42c-5b9a-4350-aca3-33cc2c752bd1.png)
해결방법이 있을까요?
config의 bot token과 id는 입력하였습니다.
upbit 공지사항만 이용하렬 하는데 혹시 최소 딜레이가 어느정되 되는지요.

**Comment by danieluhm2004** [comment]
2년 전에 작업한 프로젝트라서 실행이 안되는 것 같습니다. 업데이트 해두겠습니다~

**Comment by danieluhm2004** [comment]
안녕하세요.

최신 버전에 맞게 업데이트 완료했습니다. 다시 한 번 확인해보시면 정상적으로 작동되실 겁니다.

추가로 네트워크 환경만 좋다면 1분 이내에 감지합니다.
주기는 1분으로 설정하시는 것을 권장합니다. 너무 빠를 경우 캐싱되거나 블럭되는 경우가 있습니다.

감사합니다.
